In [1]:
#loading the data
import pandas as pd
df1 = pd.read_csv("student-scores.csv")
df = df1.copy()
df.head()

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,1,Paul,Casey,paul.casey.1@gslingacademy.com,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,2,Danielle,Sandoval,danielle.sandoval.2@gslingacademy.com,female,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,3,Tina,Andrews,tina.andrews.3@gslingacademy.com,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94
3,4,Tara,Clark,tara.clark.4@gslingacademy.com,female,False,5,False,3,Artist,71,74,88,80,89,63,86
4,5,Anthony,Campos,anthony.campos.5@gslingacademy.com,male,False,5,False,10,Unknown,84,77,65,65,80,74,76

In [2]:
#drop irrelevant columns
df.columns
df.drop(columns=['id', 'first_name', 'last_name', 'email'], inplace=True)

In [3]:
#create new feature for average score
df["total_score"] = df["math_score"] + df["history_score"] + df["physics_score"] + df["chemistry_score"] + df["biology_score"] + df["english_score"] + df["geography_score"]
df["average_score"] = df["total_score"] / 7
df.head()

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score,average_score
0,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87,574,82.000000
1,female,False,2,False,47,Doctor,90,86,96,100,90,88,90,640,91.428571
2,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94,605,86.428571
3,female,False,5,False,3,Artist,71,74,88,80,89,63,86,551,78.714286
4,male,False,5,False,10,Unknown,84,77,65,65,80,74,76,521,74.428571

In [4]:
#Encodeing categorical columns
gender_map = {'male': 0, 'female': 1}
part_time_job_map = {False: 0, True: 1}
extracurricular_activities_map = {False: 0, True: 1}
career_aspiration_map = {
        'Lawyer': 0, 'Doctor': 1, 'Government Officer': 2, 'Artist': 3, 'Unknown': 4,
        'Software Engineer': 5, 'Teacher': 6, 'Business Owner': 7, 'Scientist': 8,
        'Banker': 9, 'Writer': 10, 'Accountant': 11, 'Designer': 12,
        'Construction Engineer': 13, 'Game Developer': 14, 'Stock Investor': 15,
        'Real Estate Developer': 16
}

#Apply mapping to the dataframe
df['gender'] = df['gender'].map(gender_map)
df['part_time_job'] = df['part_time_job'].map(part_time_job_map)
df['extracurricular_activities'] = df['extracurricular_activities'].map(extracurricular_activities_map)
df['career_aspiration'] = df['career_aspiration'].map(career_aspiration_map)

In [5]:
df.head()

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score,average_score
0,0,0,3,0,27,0,73,81,93,97,63,80,87,574,82.000000
1,1,0,2,0,47,1,90,86,96,100,90,88,90,640,91.428571
2,1,0,9,1,13,2,81,97,95,96,65,77,94,605,86.428571
3,1,0,5,0,3,3,71,74,88,80,89,63,86,551,78.714286
4,0,0,5,0,10,4,84,77,65,65,80,74,76,521,74.428571

In [6]:
# Balance Dataset
df['career_aspiration'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [7]:
df['career_aspiration'].value_counts()

career_aspiration
5     315
7     309
4     223
9     169
0     138
11    126
1     119
16     83
15     73
13     68
3      67
14     63
2      61
6      59
12     56
8      39
10     32
Name: count, dtype: int64

In [8]:
from imblearn.over_sampling import SMOTE

#create SMOTE object 
smote = SMOTE(random_state = 42)

#separate features and target varaible
x = df.drop('career_aspiration', axis = 1)
y = df['career_aspiration']

# Apply SMOTE to the data
x_resampled , y_resampled = smote.fit_resample(x,y)

In [9]:
# train test split 
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x_resampled , y_resampled)

In [10]:
x_train.shape

(4016, 14)

In [11]:
y_train.shape

(4016,)

In [12]:
from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler to the training data and transform both training and testing data
X_train_scaled = scaler.fit_transform(x_train)
X_test_scaled = scaler.transform(x_test)

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import warnings
warnings.filterwarnings("ignore")

# Define models
models = {
    "Logistic Regression": LogisticRegression(),
    "Support Vector Classifier": SVC(),
    "Random Forest Classifier": RandomForestClassifier(),
    "K Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree Classifier": DecisionTreeClassifier(),
    "Gaussian Naive Bayes": GaussianNB(),
    "AdaBoost Classifier": AdaBoostClassifier(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
    "XGBoost Classifier": XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
}

# Train and evaluate each model 
for name , model in models.items():
    print("=" * 50)
    print("Model:", name)

    #train the model
    model.fit(X_train_scaled, y_train)

    #predict on test set 
    y_pred = model.predict(X_test_scaled)

    #Calculate metrics
    accuracy = accuracy_score(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    
    # Print metrics
    print("Accuracy:", accuracy)
    print("Classification Report:\n", classification_rep)
    print("Confusion Matrix:\n", conf_matrix)

==================================================
Model: Logistic Regression
Accuracy: 0.47124719940253923
Classification Report:
               precision    recall  f1-score   support

           0       0.35      0.44      0.39        70
           1       0.57      0.59      0.58        78
           2       0.39      0.31      0.35        86
           3       0.58      0.56      0.57        82
           4       0.24      0.16      0.19        77
           5       0.29      0.27      0.28        79
           6       0.50      0.82      0.63        80
           7       0.88      0.88      0.88        86
           8       0.54      0.64      0.59        64
           9       0.32      0.12      0.17        78
          10       0.60      0.67      0.63        82
          11       0.37      0.42      0.39        62
          12       0.30      0.21      0.25        99
          13       0.41      0.52      0.46        82
          14       0.60      0.81      0.69        74
          15       0.32      0.26      0.29        80
          16       0.41      0.38      0.39        80

    accuracy                           0.47      1339
   macro avg       0.45      0.47      0.45      1339
weighted avg       0.45      0.47      0.45      1339

Confusion Matrix:
 [[31  2  0  0  1 11  0  0  3  0 12  2  1  6  0  1  0]
 [ 5 46  0  0  0  5  0  0 13  0  0  0  1  8  0  0  0]
 [ 0  0 27  4  5  0 11  0  0  1  3  1 15  1  3  5 10]
 [ 0  0  5 46  0  0  7  2  0  0  0  0  0  0 13  0  9]
 [ 4  3  7  3 12  8  6  2  1  3  4  4  4  4  3  3  6]
 [ 8  5  0  0  1 21  0  0  2  8  3  9  3 12  0  7  0]
 [ 0  0  1  0  2  0 66  0  0  3  0  2  6  0  0  0  0]
 [ 0  0  0  3  0  0  0 76  0  0  0  0  0  0  3  0  4]
 [ 2 14  0  0  1  2  0  0 41  0  3  0  0  0  0  1  0]
 [15  3  1  0  7  8  8  0  3  9  5  6  3  6  0  3  1]
 [ 4  2  0  0  0  0  7  0  3  1 55  2  2  6  0  0  0]
 [ 1  1  0  0  5  5  2  0  4  0  0 26  1  7  0 10  0]
 [ 4  2 16  1  9  0  8  1  3  0  5  0 21  6 11  8  4]
 [ 7  1  1  0  2  4  0  0  3  2  1  7  4 43  0  7  0]
 [ 0  0  0  8  0  0  1  2  0  0  0  0  0  0 60  0  3]
 [ 8  2  1  0  5  8  3  0  0  1  1 12  5  6  0 21  7]
 [ 0  0 10 14  1  0 12  3  0  0  0  0  3  0  7  0 30]]
==================================================
Model: Support Vector Classifier
Accuracy: 0.6385362210604929
Classification Report:
               precision    recall  f1-score   support

           0       0.51      0.64      0.57        70
           1       0.65      0.81      0.72        78
           2       0.66      0.63      0.64        86
           3       0.74      0.70      0.72        82
           4       0.46      0.21      0.29        77
           5       0.39      0.34      0.36        79
           6       0.64      0.94      0.76        80
           7       0.89      0.92      0.90        86
           8       0.66      0.84      0.74        64
           9       0.37      0.29      0.33        78
          10       0.85      0.89      0.87        82
          11       0.70      0.42      0.53        62
          12       0.65      0.54      0.59        99
          13       0.60      0.76      0.67        82
          14       0.70      0.86      0.77        74
          15       0.60      0.47      0.53        80
          16       0.60      0.57      0.59        80

    accuracy                           0.64      1339
   macro avg       0.63      0.64      0.62      1339
weighted avg       0.63      0.64      0.62      1339

Confusion Matrix:
 [[45  4  0  0  1  3  0  0  1  2  7  0  0  3  0  4  0]
 [ 0 63  0  0  0  1  0  0  8  2  0  0  3  1  0  0  0]
 [ 0  0 54  3  6  0  7  0  0  2  0  0  3  0  2  3  6]
 [ 0  0  3 57  0  0  1  3  0  0  0  0  1  0  8  0  9]
 [ 5  3  4  1 16 11  6  3  2  3  2  4  5  1  4  4  3]
 [ 7  7  1  0  1 27  0  0  2 11  0  3  5 12  0  3  0]
 [ 0  0  0  0  1  1 75  0  0  2  0  1  0  0  0  0  0]
 [ 0  0  0  2  0  0  1 79  0  0  0  0  0  0  0  0  4]
 [ 3  7  0  0  0  0  0  0 54  0  0  0  0  0  0  0  0]
 [13  2  0  0  4  8  8  0  5 23  2  1  3  5  0  3  1]
 [ 0  1  0  0  0  0  0  0  2  3 73  0  0  3  0  0  0]
 [ 1  5  1  0  2  8  0  1  4  3  0 26  0  6  0  5  0]
 [ 5  2  6  1  2  0  9  1  2  0  0  0 53  3  9  0  6]
 [ 3  2  0  0  0  7  0  0  2  1  1  1  0 62  0  3  0]
 [ 0  0  0  6  0  0  0  2  0  0  0  0  1  0 64  0  1]
 [ 6  1  1  0  2  4  2  0  0 10  0  1  6  7  1 38  1]
 [ 0  0 12  7  0  0  8  0  0  0  1  0  2  0  4  0 46]]
==================================================
Model: Random Forest Classifier
Accuracy: 0.8252427184466019
Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.90      0.84        70
           1       0.91      0.88      0.90        78
           2       0.84      0.80      0.82        86
           3       0.86      0.95      0.90        82
           4       0.63      0.42      0.50        77
           5       0.55      0.38      0.45        79
           6       0.77      1.00      0.87        80
           7       0.98      0.94      0.96        86
           8       0.78      0.98      0.87        64
           9       0.75      0.63      0.69        78
          10       0.93      0.98      0.95        82
          11       0.87      0.77      0.82        62
          12       0.88      0.81      0.84        99
          13       0.78      0.95      0.86        82
          14       0.83      0.97      0.89        74
          15       0.84      0.81      0.83        80
          16       0.91      0.85      0.88        80

    accuracy                           0.83      1339
   macro avg       0.82      0.83      0.82      1339
weighted avg       0.82      0.83      0.82      1339

Confusion Matrix:
 [[63  0  0  0  1  3  0  0  0  1  2  0  0  0  0  0  0]
 [ 0 69  0  0  0  2  0  0  3  1  0  0  2  1  0  0  0]
 [ 0  0 69  1  6  0  6  0  0  0  0  0  0  0  3  0  1]
 [ 0  0  0 78  0  0  0  1  0  0  0  0  0  0  1  0  2]
 [ 4  1  5  5 32  7  5  1  1  1  1  1  4  2  2  4  1]
 [ 3  2  0  0  1 30  1  0  6 10  0  3  2 14  0  7  0]
 [ 0  0  0  0  0  0 80  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0 81  0  0  0  0  0  0  1  0  3]
 [ 0  1  0  0  0  0  0  0 63  0  0  0  0  0  0  0  0]
 [ 6  1  2  0  3  6  3  0  2 49  1  1  1  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  1 80  1  0  0  0  0  0]
 [ 1  1  1  0  1  4  0  0  3  0  0 48  0  2  0  1  0]
 [ 0  0  3  0  2  0  4  0  2  0  1  1 80  0  6  0  0]
 [ 1  0  0  0  0  0  0  0  1  1  1  0  0 78  0  0  0]
 [ 0  0  0  2  0  0  0  0  0  0  0  0  0  0 72  0  0]
 [ 2  1  1  0  4  3  1  0  0  1  0  0  2  0  0 65  0]
 [ 0  0  1  4  1  0  4  0  0  0  0  0  0  0  2  0 68]]
==================================================
Model: K Nearest Neighbors
Accuracy: 0.6773711725168036
Classification Report:
               precision    recall  f1-score   support

           0       0.60      0.69      0.64        70
           1       0.77      0.86      0.81        78
           2       0.68      0.74      0.71        86
           3       0.64      0.78      0.70        82
           4       0.35      0.17      0.23        77
           5       0.22      0.11      0.15        79
           6       0.75      0.91      0.82        80
           7       0.87      0.72      0.79        86
           8       0.68      0.91      0.78        64
           9       0.42      0.35      0.38        78
          10       0.80      0.91      0.85        82
          11       0.60      0.60      0.60        62
          12       0.73      0.84      0.78        99
          13       0.77      0.74      0.76        82
          14       0.76      0.84      0.79        74
          15       0.68      0.66      0.67        80
          16       0.68      0.64      0.66        80

    accuracy                           0.68      1339
   macro avg       0.65      0.67      0.65      1339
weighted avg       0.65      0.68      0.66      1339

Confusion Matrix:
 [[48  3  0  0  0  3  0  0  3  1  4  2  0  0  0  6  0]
 [ 1 67  0  0  0  0  1  0  4  2  1  0  2  0  0  0  0]
 [ 0  0 64  7  3  0  1  0  0  2  0  1  0  0  5  1  2]
 [ 0  0  4 64  0  0  3  2  0  0  0  0  1  0  3  2  3]
 [ 3  5  6  2 13  9  7  0  3  2  3  4  7  1  5  3  4]
 [10  3  3  2  6  9  0  0  7 10  2  4  6  9  1  6  1]
 [ 0  0  0  0  0  0 73  0  0  3  1  1  1  0  1  0  0]
 [ 0  0  1  6  2  0  2 62  0  2  0  1  2  0  3  0  5]
 [ 0  4  0  0  0  1  0  0 58  0  0  0  0  1  0  0  0]
 [ 7  1  0  1  4  7  3  1  4 27  6  7  5  0  1  3  1]
 [ 0  0  2  0  0  0  0  0  0  3 75  1  0  1  0  0  0]
 [ 3  2  1  0  2  4  1  2  1  3  0 37  0  2  0  3  1]
 [ 0  2  4  0  1  0  1  1  2  0  0  1 83  1  1  0  2]
 [ 4  0  0  1  3  6  0  2  1  2  1  0  0 61  0  1  0]
 [ 0  0  0  3  0  1  1  1  0  1  0  0  1  0 62  0  4]
 [ 4  0  4  2  1  1  1  0  2  5  0  1  2  3  0 53  1]
 [ 0  0  5 12  2  0  3  0  0  1  1  2  3  0  0  0 51]]
==================================================
Model: Decision Tree Classifier
Accuracy: 0.6676624346527259
Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.69      0.73        70
           1       0.80      0.81      0.80        78
           2       0.58      0.69      0.63        86
           3       0.76      0.83      0.80        82
           4       0.34      0.32      0.33        77
           5       0.32      0.27      0.29        79
           6       0.78      0.76      0.77        80
           7       0.89      0.74      0.81        86
           8       0.83      0.94      0.88        64
           9       0.50      0.45      0.47        78
          10       0.79      0.83      0.81        82
          11       0.58      0.66      0.62        62
          12       0.65      0.62      0.63        99
          13       0.70      0.73      0.71        82
          14       0.78      0.84      0.81        74
          15       0.58      0.60      0.59        80
          16       0.66      0.62      0.64        80

    accuracy                           0.67      1339
   macro avg       0.67      0.67      0.67      1339
weighted avg       0.66      0.67      0.66      1339

Confusion Matrix:
 [[48  2  0  0  2  3  0  0  0  2  3  2  2  4  0  2  0]
 [ 2 63  0  0  0  1  0  0  5  2  1  0  1  2  0  1  0]
 [ 0  0 59  0  3  2  4  1  0  2  0  2  3  1  1  2  6]
 [ 0  0  6 68  2  0  0  0  0  0  0  0  0  0  3  0  3]
 [ 6  1  4  3 25  7  4  0  1  2  2  2  7  0  2  7  4]
 [ 1  6  1  0  9 21  1  0  0  8  4 10  3  8  0  7  0]
 [ 0  0  2  0  3  0 61  0  0  6  1  1  2  0  0  0  4]
 [ 0  0  0 10  3  0  0 64  0  0  0  0  0  0  2  0  7]
 [ 0  2  0  0  1  1  0  0 60  0  0  0  0  0  0  0  0]
 [ 1  0  2  0  5 13  4  0  1 35  1  4  2  3  0  6  1]
 [ 2  1  3  0  0  1  0  0  1  5 68  0  0  0  0  1  0]
 [ 0  2  0  0  1  4  0  0  2  0  1 41  5  3  0  3  0]
 [ 1  0  6  1  7  3  1  0  1  4  1  3 61  0  7  2  1]
 [ 0  1  1  0  1  6  0  0  0  2  2  2  4 60  0  3  0]
 [ 0  0  1  2  4  0  0  4  0  0  0  0  1  0 62  0  0]
 [ 1  1  8  0  2  4  0  0  1  2  2  4  2  5  0 48  0]
 [ 0  0  8  5  6  0  3  3  0  0  0  0  1  0  3  1 50]]
==================================================
Model: Gaussian Naive Bayes
Accuracy: 0.22628827483196415
Classification Report:
               precision    recall  f1-score   support

           0       0.69      0.16      0.26        70
           1       0.45      0.19      0.27        78
           2       1.00      0.01      0.02        86
           3       0.43      0.04      0.07        82
           4       0.75      0.08      0.14        77
           5       0.32      0.15      0.21        79
           6       0.26      1.00      0.42        80
           7       0.91      0.78      0.84        86
           8       0.35      0.11      0.17        64
           9       0.00      0.00      0.00        78
          10       0.28      0.06      0.10        82
          11       0.44      0.06      0.11        62
          12       0.50      0.03      0.06        99
          13       0.10      0.93      0.18        82
          14       0.14      0.01      0.02        74
          15       0.00      0.00      0.00        80
          16       0.63      0.15      0.24        80

    accuracy                           0.23      1339
   macro avg       0.43      0.22      0.18      1339
weighted avg       0.43      0.23      0.18      1339

Confusion Matrix:
 [[11  2  0  0  0  2  0  0  1  0  4  1  0 48  0  1  0]
 [ 0 15  0  0  0  1  3  0  7  0  0  0  1 51  0  0  0]
 [ 0  0  1  0  0  0 25  0  0  1  0  0  0 58  0  0  1]
 [ 0  0  0  3  0  0 27  4  0  0  0  0  0 41  4  0  3]
 [ 0  0  0  0  6  3 21  1  0  0  0  0  0 45  0  0  1]
 [ 3  5  0  0  0 12 11  0  0  2  2  1  0 43  0  0  0]
 [ 0  0  0  0  0  0 80  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  8 67  0  0  0  0  0  8  2  0  1]
 [ 0  2  0  0  1  1  0  0  7  0  0  0  0 53  0  0  0]
 [ 1  2  0  0  0  7 21  0  1  0  4  3  1 37  0  1  0]
 [ 0  6  0  0  0  0 16  0  0  1  5  0  0 54  0  0  0]
 [ 1  0  0  0  0  2 10  0  2  1  1  4  0 41  0  0  0]
 [ 0  1  0  0  1  0 26  1  2  0  2  0  3 63  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0  0  0  0 76  0  0  0]
 [ 0  0  0  1  0  0 22  1  0  0  0  0  0 48  1  0  1]
 [ 0  0  0  0  0  4  9  0  0  0  0  0  1 66  0  0  0]
 [ 0  0  0  3  0  0 26  0  0  0  0  0  0 39  0  0 12]]
==================================================
Model: AdaBoost Classifier
Accuracy: 0.18521284540702015
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        70
           1       1.00      0.50      0.67        78
           2       0.06      0.01      0.02        86
           3       0.24      1.00      0.39        82
           4       0.08      0.53      0.14        77
           5       0.00      0.00      0.00        79
           6       0.00      0.00      0.00        80
           7       0.00      0.00      0.00        86
           8       0.32      1.00      0.48        64
           9       0.00      0.00      0.00        78
          10       0.00      0.00      0.00        82
          11       1.00      0.18      0.30        62
          12       0.03      0.03      0.03        99
          13       0.03      0.05      0.04        82
          14       0.00      0.00      0.00        74
          15       0.00      0.00      0.00        80
          16       0.20      0.04      0.06        80

    accuracy                           0.19      1339
   macro avg       0.17      0.20      0.13      1339
weighted avg       0.16      0.19      0.12      1339

Confusion Matrix:
 [[ 0  0  0  0 22  0  0  0 27  0  0  0  0 21  0  0  0]
 [ 0 39  0  0 21  0  0  0 15  0  0  0  0  3  0  0  0]
 [ 0  0  1 16 55  0  0  0  0  0  0  0  3  3  0  0  8]
 [ 0  0  0 82  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3 12 41  0  0  0 11  0  0  0  4  4  0  0  2]
 [ 0  0  0  0 41  0  0  0 19  0  0  0  8 11  0  0  0]
 [ 0  0  4  0 49  0  0  0  0  0  0  0 16 11  0  0  0]
 [ 0  0  0 86  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 64  0  0  0  0  0  0  0  0]
 [ 0  0  3  0 29  0  0  0 16  0  0  0 15 15  0  0  0]
 [ 0  0  1  0  0  0  0  0 14  0  0  0 25 42  0  0  0]
 [ 0  0  0  0 33  0  0  0 10  0  0 11  5  3  0  0  0]
 [ 0  0  0 14 70  0  0  0  3  0  0  0  3  8  0  0  1]
 [ 0  0  4  0 55  0  0  0  9  0  0  0 10  4  0  0  0]
 [ 0  0  0 74  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  1 50  0  0  0 13  0  0  0  4 10  0  0  1]
 [ 0  0  0 51 26  0  0  0  0  0  0  0  0  0  0  0  3]]
==================================================
Model: Gradient Boosting Classifier
Accuracy: 0.7162061239731142
Classification Report:
               precision    recall  f1-score   support

           0       0.65      0.79      0.71        70
           1       0.85      0.79      0.82        78
           2       0.68      0.71      0.69        86
           3       0.82      0.83      0.82        82
           4       0.58      0.29      0.38        77
           5       0.42      0.34      0.38        79
           6       0.70      0.90      0.79        80
           7       0.97      0.90      0.93        86
           8       0.70      1.00      0.83        64
           9       0.44      0.37      0.40        78
          10       0.84      0.91      0.88        82
          11       0.71      0.60      0.65        62
          12       0.81      0.66      0.73        99
          13       0.68      0.87      0.76        82
          14       0.78      0.96      0.86        74
          15       0.65      0.55      0.59        80
          16       0.72      0.74      0.73        80

    accuracy                           0.72      1339
   macro avg       0.71      0.72      0.70      1339
weighted avg       0.71      0.72      0.70      1339

Confusion Matrix:
 [[55  0  0  0  0  3  0  0  1  1  6  0  0  2  0  2  0]
 [ 0 62  0  0  1  3  0  0 10  0  0  0  0  0  0  2  0]
 [ 0  0 61  2  5  1  5  0  0  3  0  0  2  0  3  0  4]
 [ 0  0  2 68  0  0  0  1  0  0  0  0  0  0  3  0  8]
 [ 4  3  6  6 22  8  4  0  0  5  0  3  4  2  2  5  3]
 [ 7  3  0  0  1 27  0  0  4 10  1  1  3 15  0  7  0]
 [ 0  0  2  0  2  0 72  0  0  3  0  1  0  0  0  0  0]
 [ 0  0  0  3  2  0  0 77  0  0  0  0  0  0  1  0  3]
 [ 0  0  0  0  0  0  0  0 64  0  0  0  0  0  0  0  0]
 [ 8  0  1  0  2 12  6  0  3 29  5  1  1  5  0  5  0]
 [ 0  0  0  0  1  0  1  0  0  3 75  1  1  0  0  0  0]
 [ 3  4  1  0  0  2  0  0  4  5  0 37  0  4  0  2  0]
 [ 4  0  6  1  0  1  5  0  3  0  1  1 65  1  8  0  3]
 [ 1  0  2  0  0  5  0  0  2  0  0  1  0 71  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0  0 71  0  2]
 [ 3  1  2  1  1  3  4  0  0  7  1  6  3  4  0 44  0]
 [ 0  0  6  2  1  0  6  1  0  0  0  0  1  0  3  1 59]]
==================================================
Model: XGBoost Classifier
Accuracy: 0.8095593726661687
Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.89      0.81        70
           1       0.92      0.88      0.90        78
           2       0.86      0.84      0.85        86
           3       0.86      0.93      0.89        82
           4       0.63      0.44      0.52        77
           5       0.52      0.41      0.45        79
           6       0.80      0.96      0.88        80
           7       0.95      0.90      0.92        86
           8       0.82      1.00      0.90        64
           9       0.66      0.62      0.64        78
          10       0.93      0.93      0.93        82
          11       0.79      0.71      0.75        62
          12       0.92      0.78      0.84        99
          13       0.75      0.98      0.85        82
          14       0.83      0.96      0.89        74
          15       0.82      0.75      0.78        80
          16       0.83      0.81      0.82        80

    accuracy                           0.81      1339
   macro avg       0.80      0.81      0.80      1339
weighted avg       0.81      0.81      0.80      1339

Confusion Matrix:
 [[62  0  0  0  0  3  0  0  1  2  2  0  0  0  0  0  0]
 [ 0 69  0  0  0  3  0  0  4  0  0  1  0  0  0  1  0]
 [ 0  0 72  0  5  0  2  0  0  1  0  0  0  0  3  0  3]
 [ 0  0  1 76  0  0  0  2  0  0  0  0  0  0  1  0  2]
 [ 3  0  2  4 34  9  5  0  1  4  1  3  1  3  2  2  3]
 [ 8  4  0  0  0 32  1  0  2  4  0  4  2 14  0  8  0]
 [ 0  0  0  0  3  0 77  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3  0  0  0 77  0  0  0  0  0  0  2  0  4]
 [ 0  0  0  0  0  0  0  0 64  0  0  0  0  0  0  0  0]
 [ 7  0  1  0  2  8  3  0  1 48  2  0  1  5  0  0  0]
 [ 0  0  0  0  1  0  0  0  1  2 76  1  1  0  0  0  0]
 [ 1  1  0  0  0  3  0  0  3  5  0 44  1  2  0  2  0]
 [ 0  0  3  1  1  1  5  0  1  2  1  1 77  0  5  0  1]
 [ 0  1  0  0  0  0  0  0  0  0  0  1  0 80  0  0  0]
 [ 0  0  0  3  0  0  0  0  0  0  0  0  0  0 71  0  0]
 [ 2  0  3  0  3  3  0  0  0  5  0  1  1  2  0 60  0]
 [ 0  0  2  1  5  0  3  2  0  0  0  0  0  0  2  0 65]]

In [14]:
#single input predictions
print("Actual Label: ", y_test.iloc[10])
print("model prediction:", model.predict(X_test_scaled[10].reshape(1,-1))[0])
if y_test.iloc[10] == model.predict(X_test_scaled[10].reshape( 1 , -1)):
     print("wow! model doing well")

else:
     print("not sure........")

Actual Label:  8
model prediction: 8
wow! model doing well

In [26]:
# test 2
print("Actual Label :", y_test.iloc[300])
print("Model Prediction :",model.predict(X_test_scaled[300].reshape(1,-1))[0])
if y_test.iloc[300] == model.predict(X_test_scaled[300].reshape(1,-1)):
    print("Wow! Model doing well.....")
else:
    print("not sure......")

Actual Label : 6
Model Prediction : 6
Wow! Model doing well.....

In [25]:
# test 2
print("Actual Label :", y_test.iloc[0])
print("Model Prediction :",model.predict(X_test_scaled[24].reshape(1,-1))[0])
if y_test.iloc[0]==model.predict(X_test_scaled[24].reshape(1,-1)):
    print("Wow! Model doing well.....")
else:
    print("not sure......")

Actual Label : 9
Model Prediction : 14
not sure......

In [28]:
# saving and load file 
import pickle
import os

#define the directory 
model_dir = "Models"

# Create the directory if it doesnt exist 
os.makedirs(model_dir, exist_ok=True)

# SAVE FILES
with open(f"{model_dir}/scaler.pkl", 'wb') as f:
  pickle.dump(scaler, f)

with open(f"{model_dir}/model.pkl", 'wb') as f:
    pickle.dump(model, f)

In [ ]:
#save files
import pickle

# SAVE FILES
pickle.dump(scaler, open("Models/scaler.pkl", 'wb'))
pickle.dump(model, open("Models/model.pkl", 'wb'))

In [ ]:
# Load the scaler, label encoder, and model
scaler = pickle.load(open("Models/scaler.pkl", 'rb'))
model = pickle.load(open("Models/model.pkl", 'rb'))

# Recommendation System

In [29]:
import pickle
import numpy as np

# Load the scaler, label encoder, model, and class names
scaler= pickle.load(open("Models/scaler.pkl",'rb'))
model = pickle.load(open("Models/model.pkl", 'rb'))

class_names = ['Lawyer', 'Doctor', 'Government Officer', 'Artist', 'Unknown',
               'Software Engineer', 'Teacher', 'Business Owner', 'Scientist',
               'Banker', 'Writer', 'Accountant', 'Designer',
               'Construction Engineer', 'Game Developer', 'Stock Investor',
               'Real Estate Developer']


def Recommendations(gender, part_time_job, absence_days, extracurricular_activities,
                    weekly_self_study_hours, math_score, history_score, physics_score,
                    chemistry_score, biology_score, english_score, geography_score,
                    total_score,average_score):
    

    # Encode categorical variables
    gender_encoded = 1 if gender.lower() == 'female' else 0
    part_time_job_encoded = 1 if part_time_job else 0
    extracurricular_activities_encoded = 1 if extracurricular_activities else 0

     # Create feature array
    feature_array = np.array([[gender_encoded, part_time_job_encoded, absence_days, extracurricular_activities_encoded,
                               weekly_self_study_hours, math_score, history_score, physics_score,
                               chemistry_score, biology_score, english_score, geography_score,total_score,average_score]])
    

    # Scale features
    scaled_features = scaler.transform(feature_array)

    # Predict using the model
    probabilities = model.predict_proba(scaled_features)


    # Get top five predicted classes along with their probabilities
    top_classes_idx = np.argsort(-probabilities[0][:5])
    top_classes_names_probs = [(class_names[idx],probabilities[0][idx]) for idx in top_classes_idx] 
    
    return top_classes_names_probs

In [30]:
# Example usage 1
final_recommendations = Recommendations(gender='female',
                                        part_time_job=False,
                                        absence_days=2,
                                        extracurricular_activities=False,
                                        weekly_self_study_hours=7,
                                        math_score=65,
                                        history_score=60,
                                        physics_score=97,
                                        chemistry_score=94,
                                        biology_score=71,
                                        english_score=81,
                                        geography_score=66,
                                        total_score=534,
                                        average_score=76.285714)

print("Top recommended studies with probabilities:")
print("="*50)
for class_name, probability in final_recommendations:
    print(f"{class_name} with probability {probability}")

Top recommended studies with probabilities:
==================================================
Unknown with probability 0.6437495946884155
Government Officer with probability 0.006139813922345638
Doctor with probability 0.0006011755322106183
Artist with probability 0.0003730331955011934
Lawyer with probability 0.00033854105276986957

In [31]:
# Example usage 2
final_recommendations = Recommendations(gender='female',
                                        part_time_job=False,
                                        absence_days=2,
                                        extracurricular_activities=False,
                                        weekly_self_study_hours=4,
                                        math_score=87,
                                        history_score=73,
                                        physics_score=98,
                                        chemistry_score=91,
                                        biology_score=79,
                                        english_score=60,
                                        geography_score=77,
                                        total_score=583,
                                        average_score=83.285714)

print("Top recommended studies with probabilities:")
print("="*50)
for class_name, probability in final_recommendations:
    print(f"{class_name} with probability {probability}")

Top recommended studies with probabilities:
==================================================
Artist with probability 0.6854861974716187
Unknown with probability 0.0718909204006195
Government Officer with probability 0.0024964690674096346
Doctor with probability 0.001100350869819522
Lawyer with probability 0.0002621496678330004